### ISSUE TITLE
Is it possible to store data in memory and access it from another node.js process?

### ISSUE THREAD

**Issue by gajus** [samvv/diskette#2]

**Comment by samvv** [comment]
No, this library does not directly facilitate such behaviour. But it might be worthwhile checking out Node's [cluster](https://nodejs.org/api/cluster.html#cluster_event_message_1) which uses a simple IPC protocol and especially [this question](http://stackoverflow.com/questions/32618191/share-stream-with-clusters-in-nodejs).

And of course you can always create your own simple streaming IPC protocol using, for example, HTTP:

```js
const server = express()
  .get('/mydata', (req, res) => {
    res.type('octet-stream')
    new diskette.ReadableFileStream(myfile).pipe(res)
  })
server.listen(8080) // or UNIX-socket
```

And in the other process:

```js
const request = require('request')
request('http://localhost:8080/mydata').pipe(someStreamInTheOtherProcess)
```

**Comment by gajus** [comment]
> And of course you can always create your own simple streaming IPC protocol using, for example, HTTP:

The primary intention of needing to share an object in memory is to avoid serialisation/ deserialisation cost associated with converting a data structure to JSON and back to the native structure.

**Comment by gajus** [comment]
> No, this library does not directly facilitate such behaviour.

Thank you
